### ISSUE TITLE
Pipe Error

### ISSUE THREAD

**Issue by outofculture** [campagnola/scopetek#4]
My scopetek (`0547:6510 Anchor Chips Inc. USB2.0 Camera`) doesn't do well (or maybe the fault lies in my operating system; I'll try again in linux later):

```
(scopetek) @martin ~/src/scopetek (master)$ python usb_test.py
Traceback (most recent call last):
  File "usb_test.py", line 61, in <module>
    result = dev.ctrl_transfer(bmRequestType=ct[0], bRequest=ct[1], wValue=ct[2], wIndex=ct[3])
  File "/Users/martin/.virtualenvs/scopetek/lib/python2.7/site-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/Users/martin/.virtualenvs/scopetek/lib/python2.7/site-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/Users/martin/.virtualenvs/scopetek/lib/python2.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 32] Pipe error
```

**Comment by outofculture** [comment]
Ugh. My ability to diagnose things in this OS are minimal, so I have no idea what's going on with the hardware.

**Comment by campagnola** [comment]
Blast.
Does the pipe error occur on the first control transfer?
